"""
Pydantic schemas for the Kortex Extractor module.

These models define the structured schema expected from the LLM extraction layer,
acting as a bridge between intent extraction and the deterministic HTN execution engine.
"""

from typing import Any
from pydantic import BaseModel, Field


class HTNLaunchPad(BaseModel):
    """
    Schema for extracting the root task and its parameters from natural language.
    
    This object is generated by the LLM and passed directly to the HTN
    engine for deterministic planning and execution.
    """
    root_task_name: str = Field(
        ...,
        description="The canonical name of the root HTN task to be executed."
    )
    task_parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Parameters extracted from the prompt necessary to execute the task."
    )
