"""
Pydantic schemas for the Kortex Extractor module.

These models define the structured schema expected from the LLM extraction layer,
acting as a bridge between intent extraction and the deterministic HTN execution engine.
"""

from typing import Any, Union
from pydantic import BaseModel, Field

class ClarificationRequired(BaseModel):
    """
    Schema used when the natural language intent is ambiguous or missing
    mandatory parameters required by the HTN domain manifest.
    """
    question: str = Field(
        ...,
        description="The specific question to ask the user to resolve the ambiguity."
    )
    reason: str = Field(
        ...,
        description="The internal reasoning for why clarification is needed (e.g., 'Target entity type unknown: household vs individual')."
    )

class HTNLaunchPad(BaseModel):
    """
    Schema for extracting the root task and its parameters from natural language.
    
    This object is generated by the LLM and passed directly to the HTN
    engine for deterministic planning and execution.
    """
    root_task_name: str = Field(
        ...,
        description="The canonical name of the root HTN task to be executed."
    )
    task_parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Parameters extracted from the prompt necessary to execute the task."
    )

IntentExtraction = Union[HTNLaunchPad, ClarificationRequired]
